[reverse_bits]
overview = """
Reverses the order of bits in the integer. The least significant bit becomes the
most significant bit, second least-significant bit becomes second
most-significant bit, etc.
"""
examples = """
let n = $to_swap_u24;
let m = n.reverse_bits();

assert_eq!(m, $swap_b8_u24);
assert_eq!(0_u24, 0_u24.reverse_bits());
"""

[swap_bytes]
overview = """
Reverses the byte order of the integer.
"""
examples = """
let n = $to_swap_u24;
let m = n.swap_bytes();

assert_eq!(m, $swap_b1_u24);
"""

[rotate_left]
overview = """
Shifts the bits to the left by a specified amount, `n`,
wrapping the truncated bits to the end of the resulting integer.

Please note this isn't the same operation as the `<<` shifting operator!
"""
examples = """
let n = $rotate_from_u24;
let m = $rotate_into_u24;

assert_eq!(n.rotate_left($rotate_size), m);
"""

[rotate_right]
overview = """
Shifts the bits to the right by a specified amount, `n`,
wrapping the truncated bits to the beginning of the resulting integer.

Please note this isn't the same operation as the `>>` shifting operator!
"""
examples = """
let n = $rotate_into_u24;
let m = $rotate_from_u24;

assert_eq!(n.rotate_right($rotate_size), m);
"""

[count_ones]
overview = """
Returns the number of ones in the binary representation of `self`.
"""
examples = """
assert_eq!(0b01001100_u24.count_ones(), 3);
assert_eq!(0_u24.count_ones(), 0);
assert_eq!(u24::MAX.count_ones(), $bits);
"""

[count_zeros]
overview = """
Returns the number of zeros in the binary representation of `self`.
"""
examples = """
assert_eq!(0_u24.count_zeros(), $bits);
assert_eq!(u24::MAX.count_zeros(), 0);
"""

[leading_ones]
overview = """
Returns the number of leading ones in the binary representation of `self`.
"""
examples = """
assert_eq!((!(u24::MAX >> 2u32)).leading_ones(), 2);
assert_eq!(0_u24.leading_ones(), 0);
assert_eq!(u24::MAX.leading_ones(), $bits);
"""

[leading_zeros]
overview = """
Returns the number of leading zeros in the binary representation of `self`.

Depending on what you're doing with the value, you might also be interested in the
[`ilog2`] function which returns a consistent number, even if the type widens.

[`ilog2`]: Self::ilog2
"""
examples = """
assert_eq!((u24::MAX >> 2u32).leading_zeros(), 2);
assert_eq!(0_u24.leading_zeros(), $bits);
assert_eq!(u24::MAX.leading_zeros(), 0);
"""

[trailing_ones]
overview = """
Returns the number of trailing ones in the binary representation of `self`.
"""
examples = """
assert_eq!(0b01010111_u24.trailing_ones(), 3);
assert_eq!(0_u24.trailing_ones(), 0);
assert_eq!(u24::MAX.trailing_ones(), $bits);
"""

[trailing_zeros]
overview = """
Returns the number of trailing zeros in the binary representation of `self`.
"""
examples = """
assert_eq!(0b00101000_u24.trailing_zeros(), 3);
assert_eq!(0_u24.trailing_zeros(), $bits);
assert_eq!(u24::MAX.trailing_zeros(), 0);
"""

[isolate_highest_one]
overview = """
Returns `self` with only the most significant bit set, or `0` if the input is `0`.
"""
examples = """
assert_eq!(0b01100100_u24.isolate_highest_one(), 0b01000000_u24);
assert_eq!(0_u24.isolate_highest_one(), 0_u24);
"""

[isolate_lowest_one]
overview = """
Returns `self` with only the least significant bit set, or `0` if the input is `0`.
"""
examples = """
assert_eq!(0b01100100_u24.isolate_lowest_one(), 0b00000100_u24);
assert_eq!(0_u24.isolate_lowest_one(), 0_u24);
"""

[highest_one]
overview = """
Returns the index of the highest bit set to one in `self`, or `None` if `self` is `0`.
"""
examples = """
assert_eq!(0x0_u24.highest_one(), None);
assert_eq!(0x1_u24.highest_one(), Some(0));
assert_eq!(0x10_u24.highest_one(), Some(4));
assert_eq!(0x1f_u24.highest_one(), Some(4));
"""

[lowest_one]
overview = """
Returns the index of the lowest bit set to one in `self`, or `None` if `self` is `0`.
"""
examples = """
assert_eq!(0x0_u24.lowest_one(), None);
assert_eq!(0x1_u24.lowest_one(), Some(0));
assert_eq!(0x10_u24.lowest_one(), Some(4));
assert_eq!(0x1f_u24.lowest_one(), Some(0));
"""

[bit_width]
overview = """
Returns the minimum number of bits required to represent `self`.

This method returns zero if `self` is zero.
"""
examples = """
assert_eq!(0_u24.bit_width(), 0);
assert_eq!(0b111_u24.bit_width(), 3);
assert_eq!(0b1110_u24.bit_width(), 4);
assert_eq!(u24::MAX.bit_width(), $bits);
"""
