[BITS]
overview = """
The size of this integer type in bits.
"""
examples = """
assert_eq!(u24::BITS, $bits);
"""

[MAX]
overview = """
The largest value that can be represented by this integer type. (2<sup>$bits</sup> &minus; 1).
"""
examples = """
assert_eq!(u24::MAX, $uint_max_u24);
"""

[MIN]
overview = """
The smallest value that can be represented by this integer type.
"""
examples = """
assert_eq!(u24::MIN, $uint_min_u24);
"""
